project:
  type: book
  output-dir: docs

book:
  title: "Creating LFE Database from Unstructured DAta"
  author: ""
  date: "15/02/2024"
  chapters:
    - index.qmd
    - using-chat-gpt-with-r.qmd
    - using-chat-gpt-to-extract-data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo