project:
  type: website
  render: 
    - "*.qmd"

website:
  title: "Developing LFE Database"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lajh87/lfedb

format:
  html:
    theme: cosmo
    css: styles.css



