# Using Chat GPT with R

You will need to load your open ai key as an environment variable. The simplest way to do this is 

```
file.edit("~/.Renviron")
OPEN_API_KEY = <INSERT OPEN AI KEY>
```

Save then restart R. 

You can access the key as follows.

```{r}
key <- Sys.getenv("OPENAI_API_KEY")

```

There is an openai package from cran. It is still being developed and subject to change.

```{r}
library(openai)
out <- create_chat_completion(
    model = "gpt-3.5-turbo",
    messages = list(
        list(
            "role" = "system",
            "content" = "You are a helpful assistant."
        ),
        list(
            "role" = "user",
            "content" = "Who won the world series in 2020?"
        ),
        list(
            "role" = "assistant",
            "content" = "The Los Angeles Dodgers won the World Series in 2020."
        ),
        list(
            "role" = "user",
            "content" = "Where was it played?"
        )
    )
)

out$choices$message.content
```

It may well be safer to run a `httr::POST` request instead using the following function.

```{r}
library(httr)
resp <- POST(url = "https://api.openai.com/v1/chat/completions",
     add_headers(`Content-Type` = "application/json",
                   Authorization = glue::glue("Bearer {key}")),
     body = '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }')

content(resp)
     
```
